language: python
python: 2.7
addons:
  postgresql: 9.6
env:
  global:
  - TESTMODEL_URL=http://localhost:8080/intermine-demo
  - TESTMODEL_PATH=intermine-demo
  - TERM=dumb
sudo: true
jdk:
- openjdk8
script:
- "./config/travis/run.sh"
