name: InterMinr Java Client CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate JavDoc for InterMine WS Java Client 
      run: ./gradlew generateInterMineJavadoc
